In [1]:
import pandas as pd
import os
from geopy.geocoders import Nominatim
import pandas as pd
import time
import numpy as np

## Importar e salvar os conjuntos de dados referente a feature engineering.

In [19]:
import osmnx as ox

cidade = "São Paulo, São Paulo, Brasil"

#-----------------------------------------------------
tags_hospitais = {"amenity": "hospital"}

hospitais = ox.features_from_place(cidade, tags_hospitais)
#----------------------------------------------------------

mercados = ox.features_from_place(
    cidade,
    {"shop": ["supermarket", "convenience"]}
)

#---------------------------------------------------------
farmacias = ox.features_from_place(
    cidade,
    {"amenity": "pharmacy"}
)

parques = ox.features_from_place(
    cidade,
    tags={
        "leisure": ["park", "garden"],
        "landuse": "recreation_ground"
    }
)

# -----------------------------------------------------
# Estações de metrô
metro_stations = ox.features_from_place(
    cidade,
    tags={
        "railway": "station",
        "station": "subway"
    }
)

# -----------------------------------------------------
# Entradas de metrô (opcional, mas aumenta cobertura)
metro_entrances = ox.features_from_place(
    cidade,
    tags={"railway": "subway_entrance"}
)

In [20]:
metro = pd.concat([metro_stations, metro_entrances])
metro

                                                              geometry  \
element id
node    60634870                           POINT (-46.62513 -23.51564)
        176004373                          POINT (-46.63572 -23.55496)
        605663613                           POINT (-46.69112 -23.5465)
        1658464892                         POINT (-46.63361 -23.53707)
        2380750804                           POINT (-46.6523 -23.5978)
...                                                                ...
        12917913487                         POINT (-46.64118 -23.5756)
        12992303449                         POINT (-46.6126 -23.60198)
        12992303450                        POINT (-46.61241 -23.60226)
        13608665318                        POINT (-46.73504 -23.59289)
way     1095188246   POLYGON ((-46.69251 -23.63362, -46.69231 -23.6...

                                     name public_transport          railway  \
element id
node    60634870       Portuguesa - Tietê    stop_position             stop
        176004373       Japão - Liberdade    stop_position             stop
        605663613           Vila Madalena          station          station
        1658464892                    Luz    stop_position             stop
        2380750804        AACD – Servidor    stop_position             stop
...                                   ...              ...              ...
        12917913487  Parada Metro Paraiso              NaN  subway_entrance
        12992303449                   NaN              NaN  subway_entrance
        12992303450                   NaN              NaN  subway_entrance
        13608665318                   NaN              NaN  subway_entrance
way     1095188246     Estação Borba Gato              NaN  subway_entrance

                     ref station subway   old_name  \
element id
node    60634870     TTE  subway    yes        NaN
        176004373    LIB  subway    yes  Liberdade
        605663613    VMD  subway    yes        NaN
        1658464892   LUZ  subway    yes        NaN
        2380750804   NaN  subway    yes        NaN
...                  ...     ...    ...        ...
        12917913487  NaN     NaN    NaN        NaN
        12992303449    A     NaN    NaN        NaN
        12992303450    B     NaN    NaN        NaN
        13608665318  NaN     NaN    NaN        NaN
way     1095188246   NaN     NaN    NaN        NaN

                                       operator   wikidata  ... type highway  \
element id                                                  ...
node    60634870                            NaN        NaN  ...  NaN     NaN
        176004373                           NaN        NaN  ...  NaN     NaN
        605663613    Metropolitano de São Paulo   Q5244825  ...  NaN     NaN
        1658464892                          NaN  Q15243160  ...  NaN     NaN
        2380750804                          NaN   Q5908613  ...  NaN     NaN
...                                         ...        ...  ...  ...     ...
        12917913487                     SPTrans        NaN  ...  NaN     NaN
        12992303449                         NaN        NaN  ...  NaN     NaN
        12992303450                         NaN        NaN  ...  NaN     NaN
        13608665318                         NaN        NaN  ...  NaN     NaN
way     1095188246                          NaN   Q4944343  ...  NaN     NaN

                    waterway access entrance       description is_in level  \
element id
node    60634870         NaN    NaN      NaN               NaN   NaN   NaN
        176004373        NaN    NaN      NaN               NaN   NaN   NaN
        605663613        NaN    NaN      NaN               NaN   NaN   NaN
        1658464892       NaN    NaN      NaN               NaN   NaN   NaN
        2380750804       NaN    NaN      NaN               NaN   NaN   NaN
...                      ...    ...      ...               ...   ...   ...
        12917913487      NaN    yes      NaN               NaN   NaN     0
        12992303449      NaN    NaN      NaN               NaN   NaN   NaN
        12992303450      NaN    NaN      NaN               NaN   NaN   NaN
        13608665318      NaN    NaN      NaN  Entrada de metrô   NaN     2
way     1095188246       NaN    NaN      NaN               NaN   NaN   NaN

                    departures_board elevator
element id
node    60634870                 NaN      NaN
        176004373                NaN      NaN
        605663613                NaN      NaN
        1658464892               NaN      NaN
        2380750804               NaN      NaN
...                              ...      ...
        12917913487              yes      yes
        12992303449              NaN      NaN
        12992303450              NaN      NaN
        13608665318              NaN      NaN
way     1095188246               NaN      NaN

[392 rows x 77 columns]

In [21]:
escolas = ox.features_from_place(
    cidade,
    tags={
        "amenity": ["school", "college", "university"]
    }
)
escolas

                                                             geometry  \
element id
node    507071835                         POINT (-46.73411 -23.52802)
        525522286                         POINT (-46.70408 -23.63375)
        609954917                         POINT (-46.73654 -23.52544)
        638425993                         POINT (-46.59965 -23.54121)
        696175114                         POINT (-46.69814 -23.63585)
...                                                               ...
way     1486512187  POLYGON ((-46.50114 -23.59593, -46.501 -23.595...
        1486698682  POLYGON ((-46.52864 -23.52461, -46.52867 -23.5...
        1486707690  POLYGON ((-46.56626 -23.52754, -46.56612 -23.5...
        1486962631  POLYGON ((-46.56422 -23.53526, -46.56417 -23.5...
        1488713496  POLYGON ((-46.65993 -23.4808, -46.65988 -23.48...

                       amenity                                     name  \
element id
node    507071835      college       Universidade Mogi das Cruzes (UMC)
        525522286       school                                      NaN
        609954917   university             Universidade Mogi das Cruzes
        638425993       school            Colégio Presbiteriano do Brás
        696175114       school                              Coreo Dança
...                        ...                                      ...
way     1486512187      school  E.E. Professor Victorio Américo Fontana
        1486698682      school              E.E Dom João Maria Ogno Osb
        1486707690     college                                    Senai
        1486962631      school                E.E Joao Dias da Silveira
        1488713496      school    Centro Brasileiro de Insino Intregado

                   addr:housenumber                    addr:street check_date  \
element id
node    507071835               NaN                            NaN        NaN
        525522286               NaN                            NaN        NaN
        609954917               550  Avenida Imperatriz Leopoldina        NaN
        638425993               NaN                            NaN        NaN
        696175114               NaN                            NaN        NaN
...                             ...                            ...        ...
way     1486512187              117                 Rua Nepomuceno        NaN
        1486698682              304              Rua Maria Carlota        NaN
        1486707690              NaN                            NaN        NaN
        1486962631               80               Rua Sousa Breves        NaN
        1488713496             1482    Rua Joaquim Afonso de Souza        NaN

                   name:en wheelchair wikidata wikipedia  ...  \
element id                                                ...
node    507071835      NaN        NaN      NaN       NaN  ...
        525522286      NaN        NaN      NaN       NaN  ...
        609954917      NaN        NaN      NaN       NaN  ...
        638425993      NaN        NaN      NaN       NaN  ...
        696175114      NaN        NaN      NaN       NaN  ...
...                    ...        ...      ...       ...  ...
way     1486512187     NaN        NaN      NaN       NaN  ...
        1486698682     NaN        NaN      NaN       NaN  ...
        1486707690     NaN        NaN      NaN       NaN  ...
        1486962631     NaN        NaN      NaN       NaN  ...
        1488713496     NaN        NaN      NaN       NaN  ...

                   payment:mastercard payment:pikepass payment:uta  \
element id
node    507071835                 NaN              NaN         NaN
        525522286                 NaN              NaN         NaN
        609954917                 NaN              NaN         NaN
        638425993                 NaN              NaN         NaN
        696175114                 NaN              NaN         NaN
...                               ...              ...         ...
way     1486512187                NaN              NaN         NaN
        1486698682                NaN              NaN         NaN
        1486707690                NaN              NaN         NaN
        1486962631                NaN              NaN         NaN
        1488713496                NaN              NaN         NaN

                   payment:visa payment:visa_debit payment:visa_electron area  \
element id
node    507071835           NaN                NaN                   NaN  NaN
        525522286           NaN                NaN                   NaN  NaN
        609954917           NaN                NaN                   NaN  NaN
        638425993           NaN                NaN                   NaN  NaN
        696175114           NaN                NaN                   NaN  NaN
...                         ...                ...                   ...  ...
way     1486512187          NaN                NaN                   NaN  NaN
        1486698682          NaN                NaN                   NaN  NaN
        1486707690          NaN                NaN                   NaN  NaN
        1486962631          NaN                NaN                   NaN  NaN
        1488713496          NaN                NaN                   NaN  NaN

                   surface related_law access:conditional
element id
node    507071835      NaN         NaN                NaN
        525522286      NaN         NaN                NaN
        609954917      NaN         NaN                NaN
        638425993      NaN         NaN                NaN
        696175114      NaN         NaN                NaN
...                    ...         ...                ...
way     1486512187     NaN         NaN                NaN
        1486698682     NaN         NaN                NaN
        1486707690     NaN         NaN                NaN
        1486962631     NaN         NaN                NaN
        1488713496     NaN         NaN                NaN

[1837 rows x 168 columns]

In [22]:
escolas["geometry_std"] = escolas.geometry.apply(
    lambda g: g.centroid if g.geom_type != "Point" else g
)

escolas_std = escolas.set_geometry("geometry_std")
escolas_std.geometry.geom_type.value_counts()

Point    1837
Name: count, dtype: int64

In [23]:
import re
import pandas as pd

def classificar_escola(row):
    nome = str(row.get("name", "")).lower()

    padroes_publicos = [
        "municipal",
        "estadual",
        "federal",
        "instituto federal",
        "colégio estadual",
        "escola municipal",
        "cmei", "emei", "emef", "eef", "eeef",
        "universidade federal",
        "universidade estadual",
        "ifpr", "ifsp", "ifsc", "ifrs"
    ]

    for p in padroes_publicos:
        if p in nome:
            return "publica"

    return "privada"

escolas_std["tipo_escola"] = escolas_std.apply(classificar_escola, axis=1)

In [24]:
escolas_std["tipo_escola"].value_counts(normalize=True)

tipo_escola
privada    0.634731
publica    0.365269
Name: proportion, dtype: float64

In [25]:
policia = ox.features_from_place(
    cidade,
    tags={
        "amenity": ["police", "fire_station", "courthouse"]
    }
)
policia

                                                             geometry  \
element id
node    180576749                         POINT (-46.56461 -23.53986)
        468049990                         POINT (-46.49832 -23.51011)
        470109183                         POINT (-46.70454 -23.50965)
        507071859                         POINT (-46.73081 -23.53873)
        745730429                         POINT (-46.65028 -23.53932)
...                                                               ...
way     1470430534  POLYGON ((-46.64872 -23.45658, -46.64866 -23.4...
        1473347960  POLYGON ((-46.49213 -23.55385, -46.49213 -23.5...
        1486530148  POLYGON ((-46.5673 -23.53697, -46.56721 -23.53...
        1488015882  POLYGON ((-46.56799 -23.53172, -46.56782 -23.5...
        1488015883  POLYGON ((-46.56809 -23.5314, -46.56755 -23.53...

                         amenity  \
element id
node    180576749   fire_station
        468049990         police
        470109183         police
        507071859         police
        745730429         police
...                          ...
way     1470430534        police
        1473347960        police
        1486530148        police
        1488015882    courthouse
        1488015883    courthouse

                                                                 name  \
element id
node    180576749                          Corpo de Bombeiros - 3º GB
        468049990                               24º Distrito Policial
        470109183                                     Policia Militar
        507071859                              91o. Distrito Policial
        745730429                               Ponto Policia Militar
...                                                               ...
way     1470430534                                                NaN
        1473347960  66º Distrito Policial / 8ª DDM - Delegacia de ...
        1486530148                         Polícia Militar - 8º BPM/M
        1488015882                                Forum Regional VIII
        1488015883                          TJSP Almoxerifado Central

                                                             operator  \
element id
node    180576749   Corpo de Bombeiros Militar do Estado de São Paulo
        468049990                Polícia Civil do Estado de São Paulo
        470109183              Polícia Militar do Estado de São Paulo
        507071859                Polícia Civil do Estado de São Paulo
        745730429                                                 NaN
...                                                               ...
way     1470430534             Polícia Militar do Estado de São Paulo
        1473347960               Polícia Civil do Estado de São Paulo
        1486530148             Polícia Militar do Estado de São Paulo
        1488015882         Tribunal de Justiça do Estado de São Paulo
        1488015883                                                NaN

                   operator:wikidata   landuse military operator:short  \
element id
node    180576749          Q10260738       NaN      NaN            NaN
        468049990          Q10350993       NaN      NaN            NaN
        470109183          Q10351025  military   police          PMESP
        507071859          Q10350993       NaN      NaN            NaN
        745730429                NaN       NaN      NaN            NaN
...                              ...       ...      ...            ...
way     1470430534         Q10351025       NaN      NaN          PMESP
        1473347960         Q10350993       NaN      NaN            NaN
        1486530148         Q10351025  military   police          PMESP
        1488015882        Q125454187       NaN      NaN            NaN
        1488015883               NaN       NaN      NaN            NaN

                    addr:city addr:housenumber  ... leisure wikimedia_commons  \
element id                                      ...
node    180576749         NaN              NaN  ...     NaN               NaN
        468049990         NaN              NaN  ...     NaN               NaN
        470109183         NaN              NaN  ...     NaN               NaN
        507071859         NaN              NaN  ...     NaN               NaN
        745730429         NaN              NaN  ...     NaN               NaN
...                       ...              ...  ...     ...               ...
way     1470430534  São Paulo              NaN  ...     NaN               NaN
        1473347960  São Paulo              190  ...     NaN               NaN
        1486530148  São Paulo              307  ...     NaN               NaN
        1488015882  São Paulo              NaN  ...     NaN               NaN
        1488015883  São Paulo               50  ...     NaN               NaN

                   area operator:type addr:district  lit  surface type  \
element id
node    180576749   NaN           NaN           NaN  NaN      NaN  NaN
        468049990   NaN           NaN           NaN  NaN      NaN  NaN
        470109183   NaN           NaN           NaN  NaN      NaN  NaN
        507071859   NaN           NaN           NaN  NaN      NaN  NaN
        745730429   NaN           NaN           NaN  NaN      NaN  NaN
...                 ...           ...           ...  ...      ...  ...
way     1470430534  NaN           NaN           NaN  yes  asphalt  NaN
        1473347960  NaN           NaN           NaN  NaN      NaN  NaN
        1486530148  NaN           NaN           NaN  NaN      NaN  NaN
        1488015882  NaN           NaN           NaN  NaN      NaN  NaN
        1488015883  NaN           NaN           NaN  NaN      NaN  NaN

                   official_name loc_name
element id
node    180576749            NaN      NaN
        468049990            NaN      NaN
        470109183            NaN      NaN
        507071859            NaN      NaN
        745730429            NaN      NaN
...                          ...      ...
way     1470430534           NaN      NaN
        1473347960           NaN      NaN
        1486530148           NaN      NaN
        1488015882           NaN      NaN
        1488015883           NaN      NaN

[454 rows x 97 columns]

In [26]:
escolas_std.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/escolas_sp.csv",
    index=False
)

hospitais.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/hospitais_sp.csv",
    index=False
)

parques.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/parques_sp.csv",
    index=False
)

mercados.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/mercados_sp.csv",
    index=False
)

farmacias.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/farmacia_sp.csv",
    index=False
)

policia.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/policia_sp.csv",
    index=False
)

In [27]:
metro.to_csv(
    "/home/felipe/Projeto/Portfolio/Portfolio2/"
    "Regression_PriceHouse/data/pre/metro_sp.csv",
    index=False
)