In [8]:
import requests

cookies = {
    '5ANNEX': 'eyJ1dWlkIjoieFdPSXRmbm9qdUJRZTIxNWZoaEJjNDlUMEpxcXlUdDBNem5HUVh3VFlaeDBJa2RGVXJaZkxnIiwiZiI6W3siayI6InJjX2JlYWttYW5faGxzX2Rpc2FibGUiLCJ2Ijp0cnVlLCJ0IjoiciJ9LHsiayI6InJjX2JlYWttYW5fc2F2ZV9sZWFkX3YyX2VuYWJsZWQiLCJ2Ijp0cnVlLCJ0IjoiciJ9LHsiayI6ImFiX2JlYWttYW5fc2hvcnRfZGVzY3JpcHRpb25fZW5hYmxlZCIsInYiOjEsInQiOiJpIn0seyJrIjoiYWJfYmVha21hbl9zZWFyY2hfc2VydmljZXNfbG9jYXRpb25fZW1iZWRkaW5nX29uX2NnX2V4cGVyaW1lbnQiLCJ2IjoxLCJ0IjoiaSJ9XX0%3D',
    'ab.storage.sessionId.cf9e8c77-7b32-4126-940b-b58658d0918e': '%7B%22g%22%3A%220cff7673-2888-7a5b-51f2-4880d8772d52%22%2C%22e%22%3A1773504695252%2C%22c%22%3A1773502623706%2C%22l%22%3A1773502895252%7D',
    'ab.storage.deviceId.cf9e8c77-7b32-4126-940b-b58658d0918e': '%7B%22g%22%3A%2244dea564-148c-e030-22c3-4daf33388b84%22%2C%22c%22%3A1773502623707%2C%22l%22%3A1773502623707%7D',
    'amplitude_id_3fbf25d58c3cce92f0e6609904a37cc9quintoandar.com.br': 'eyJkZXZpY2VJZCI6InhXT0l0Zm5vanVCUWUyMTVmaGhCYzQ5VDBKcXF5VHQwTXpuR1FYd1RZWngwSWtkRlVyWmZMZyIsInVzZXJJZCI6bnVsbCwib3B0T3V0IjpmYWxzZSwic2Vzc2lvbklkIjoxNzczNTAyNjIzODM5LCJsYXN0RXZlbnRUaW1lIjoxNzczNTAyOTAwNTM0LCJldmVudElkIjo2MiwiaWRlbnRpZnlJZCI6NTUsInNlcXVlbmNlTnVtYmVyIjoxMTd9',
    '5A_SESSION_ID': '1773502624041',
    '_egw': '1773502625353.6b8cb2b6-28a5-417e-9cb5-451ede0415fb',
    '_hjSessionUser_1203740': 'eyJpZCI6ImNiMGE1NTEzLTBlMWItNWMyZC04N2I3LTNiN2RhZjQ5OWIyMSIsImNyZWF0ZWQiOjE3NzM1MDI2MjcxOTEsImV4aXN0aW5nIjp0cnVlfQ==',
    '_hjSession_1203740': 'eyJpZCI6Ijc4ZDEwOWUxLTkwNzAtNGE4Yy1iMjljLTk3M2Q5ZDFjYmZkNSIsImMiOjE3NzM1MDI2MjcxOTEsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjoxLCJzcCI6MH0=',
    'crto_is_user_optout': 'false',
    'crto_mapped_user_id': 'KHc-Pl9TZ0N2Sm0zeXR1ZTFsYlR6YTR3WGo0ZXpWVm1JNlNucHUlMkZjZDVLTGVEU1FxZE1kN2h3SUMlMkJKSFo3ZnVMTDdPVA',
    '_ga_E2JVTQ7D7Q': 'GS2.1.s1773502627$o1$g0$t1773502900$j57$l0$h929917408',
    '_ga': 'GA1.1.422027370.1773502628',
    'FPID': 'FPID2.3.GAX0b3CUWZNiovpvlllrrPqh2fYCb7rwT%2BlzOmZsSoY%3D.1773502628',
    'FPLC': 'h3HCQ2NbAohdX%2FoQeX3rU85u%2FUirh8ByxqFpSPnDF1blzvcJ7fjqjHHaaXJSd8fE3JQ1SSsyexWhnx33LLO1xgbfJGWPxXoiEN2oUn7T9WLcbyZD0F9g1pB9eSsdZw%3D%3D',
    'FPAU': '1.3.1375725850.1773502628',
    '_fbp': 'fb.2.1773502628072.1504329516',
    'FPGCLAW': '2.1.kCjwKCAjwjtTNBhB0EiwAuswYhpD-aDxe7I3trTGUDLbZaNCttrYsJ7HHngVBV4nV6mQ2pW44fQ7ryxoCH0kQAvD_BwE$i1773502901',
    'FPGCLGS': '2.1.k1$i1773502623$u211528725',
    '_ga_2NHZ8V3TH0': 'GS2.1.s1773502635$o1$g0$t1773502900$j60$l0$h1611355509',
}

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:148.0) Gecko/20100101 Firefox/148.0',
    'Accept': 'application/json',
    'Accept-Language': 'pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7',
    # 'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Content-Type': 'application/json',
    'X-AB-Test': 'ab_beakman_search_services_demand_concentration_v1_map_and_ssr_rent_experiment_v2:1,ab_beakman_search_services_demand_sufficiency_v1_sale_experiment:-1,ab_beakman_search_services_demand_sufficiency_v1_sale_experiment_rollout:false,ab_beakman_search_services_demand_sufficiency_v1_sale_experiment_rollout_v1:false,ab_beakman_search_services_demand_sufficiency_v1_sale_experiment_v1:-1,ab_beakman_search_services_feed_filter_search_profile_experiment:1,ab_beakman_search_services_hue_candidate_generation_experiment_v2:-1,ab_beakman_search_services_location_embedding_on_cg_experiment:1,ab_beakman_search_services_open_search_find:1,ab_beakman_search_services_open_search_migration:true,ab_beakman_search_services_open_search_migration_rollout:true,ab_beakman_search_services_p_click_experiment_sale_v7:1,ab_beakman_search_services_p_click_experiment_v7:0',
    'Origin': 'https://www.quintoandar.com.br',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'Connection': 'keep-alive',
    # 'Cookie': '5ANNEX=eyJ1dWlkIjoieFdPSXRmbm9qdUJRZTIxNWZoaEJjNDlUMEpxcXlUdDBNem5HUVh3VFlaeDBJa2RGVXJaZkxnIiwiZiI6W3siayI6InJjX2JlYWttYW5faGxzX2Rpc2FibGUiLCJ2Ijp0cnVlLCJ0IjoiciJ9LHsiayI6InJjX2JlYWttYW5fc2F2ZV9sZWFkX3YyX2VuYWJsZWQiLCJ2Ijp0cnVlLCJ0IjoiciJ9LHsiayI6ImFiX2JlYWttYW5fc2hvcnRfZGVzY3JpcHRpb25fZW5hYmxlZCIsInYiOjEsInQiOiJpIn0seyJrIjoiYWJfYmVha21hbl9zZWFyY2hfc2VydmljZXNfbG9jYXRpb25fZW1iZWRkaW5nX29uX2NnX2V4cGVyaW1lbnQiLCJ2IjoxLCJ0IjoiaSJ9XX0%3D; ab.storage.sessionId.cf9e8c77-7b32-4126-940b-b58658d0918e=%7B%22g%22%3A%220cff7673-2888-7a5b-51f2-4880d8772d52%22%2C%22e%22%3A1773504695252%2C%22c%22%3A1773502623706%2C%22l%22%3A1773502895252%7D; ab.storage.deviceId.cf9e8c77-7b32-4126-940b-b58658d0918e=%7B%22g%22%3A%2244dea564-148c-e030-22c3-4daf33388b84%22%2C%22c%22%3A1773502623707%2C%22l%22%3A1773502623707%7D; amplitude_id_3fbf25d58c3cce92f0e6609904a37cc9quintoandar.com.br=eyJkZXZpY2VJZCI6InhXT0l0Zm5vanVCUWUyMTVmaGhCYzQ5VDBKcXF5VHQwTXpuR1FYd1RZWngwSWtkRlVyWmZMZyIsInVzZXJJZCI6bnVsbCwib3B0T3V0IjpmYWxzZSwic2Vzc2lvbklkIjoxNzczNTAyNjIzODM5LCJsYXN0RXZlbnRUaW1lIjoxNzczNTAyOTAwNTM0LCJldmVudElkIjo2MiwiaWRlbnRpZnlJZCI6NTUsInNlcXVlbmNlTnVtYmVyIjoxMTd9; 5A_SESSION_ID=1773502624041; _egw=1773502625353.6b8cb2b6-28a5-417e-9cb5-451ede0415fb; _hjSessionUser_1203740=eyJpZCI6ImNiMGE1NTEzLTBlMWItNWMyZC04N2I3LTNiN2RhZjQ5OWIyMSIsImNyZWF0ZWQiOjE3NzM1MDI2MjcxOTEsImV4aXN0aW5nIjp0cnVlfQ==; _hjSession_1203740=eyJpZCI6Ijc4ZDEwOWUxLTkwNzAtNGE4Yy1iMjljLTk3M2Q5ZDFjYmZkNSIsImMiOjE3NzM1MDI2MjcxOTEsInMiOjAsInIiOjAsInNiIjowLCJzciI6MCwic2UiOjAsImZzIjoxLCJzcCI6MH0=; crto_is_user_optout=false; crto_mapped_user_id=KHc-Pl9TZ0N2Sm0zeXR1ZTFsYlR6YTR3WGo0ZXpWVm1JNlNucHUlMkZjZDVLTGVEU1FxZE1kN2h3SUMlMkJKSFo3ZnVMTDdPVA; _ga_E2JVTQ7D7Q=GS2.1.s1773502627$o1$g0$t1773502900$j57$l0$h929917408; _ga=GA1.1.422027370.1773502628; FPID=FPID2.3.GAX0b3CUWZNiovpvlllrrPqh2fYCb7rwT%2BlzOmZsSoY%3D.1773502628; FPLC=h3HCQ2NbAohdX%2FoQeX3rU85u%2FUirh8ByxqFpSPnDF1blzvcJ7fjqjHHaaXJSd8fE3JQ1SSsyexWhnx33LLO1xgbfJGWPxXoiEN2oUn7T9WLcbyZD0F9g1pB9eSsdZw%3D%3D; FPAU=1.3.1375725850.1773502628; _fbp=fb.2.1773502628072.1504329516; FPGCLAW=2.1.kCjwKCAjwjtTNBhB0EiwAuswYhpD-aDxe7I3trTGUDLbZaNCttrYsJ7HHngVBV4nV6mQ2pW44fQ7ryxoCH0kQAvD_BwE$i1773502901; FPGCLGS=2.1.k1$i1773502623$u211528725; _ga_2NHZ8V3TH0=GS2.1.s1773502635$o1$g0$t1773502900$j60$l0$h1611355509',
    'Priority': 'u=4',
    # Requests doesn't support trailers
    # 'TE': 'trailers',
}

json_data = {
    'context': {
        'mapShowing': True,
        'listShowing': True,
        'userId': 'xWOItfnojuBQe215fhhBc49T0JqqyTt0MznGQXwTYZx0IkdFUrZfLg',
        'deviceId': 'xWOItfnojuBQe215fhhBc49T0JqqyTt0MznGQXwTYZx0IkdFUrZfLg',
        'numPhotos': 12,
        'isSSR': False,
    },
    'filters': {
        'businessContext': 'RENT',
        'blocklist': [],
        'selectedHouses': [],
        'location': {
            'coordinate': {
                'lat': -23.55052,
                'lng': -46.633309,
            },
            'viewport': {
                'east': -46.50439130590819,
                'north': -23.504561866351537,
                'south': -23.596462071688684,
                'west': -46.76222669409179,
            },
            'neighborhoods': [],
            'countryCode': 'BR',
        },
        'priceRange': [],
        'specialConditions': [],
        'excludedSpecialConditions': [],
        'houseSpecs': {
            'area': {
                'range': {},
            },
            'houseTypes': [],
            'amenities': [],
            'installations': [],
            'bathrooms': {
                'range': {},
            },
            'bedrooms': {
                'range': {},
            },
            'parkingSpace': {
                'range': {},
            },
            'suites': {
                'range': {},
            },
        },
        'availability': 'ANY',
        'occupancy': 'ANY',
        'partnerIds': [],
        'categories': [],
        'enableFlexibleSearch': True,
    },
    'sorting': {
        'criteria': 'RELEVANCE',
        'order': 'DESC',
    },
    'pagination': {
        'pageSize': 12,
        'offset': 0,
    },
    'slug': 'sao-paulo-sp-brasil',
    'fields': [
        'id',
        'coverImage',
        'rent',
        'totalCost',
        'salePrice',
        'iptuPlusCondominium',
        'area',
        'imageList',
        'imageCaptionList',
        'address',
        'regionName',
        'city',
        'visitStatus',
        'activeSpecialConditions',
        'type',
        'forRent',
        'forSale',
        'isPrimaryMarket',
        'bedrooms',
        'parkingSpaces',
        'suites',
        'listingTags',
        'yield',
        'yieldStrategy',
        'neighbourhood',
        'categories',
        'bathrooms',
        'isFurnished',
        'installations',
        'amenities',
        'shortRentDescription',
        'shortSaleDescription',
    ],
    'locationDescriptions': [
        {
            'description': 'sao-paulo-sp-brasil',
        },
    ],
    'topics': [],
}

response = requests.post(
    'https://apigw.prod.quintoandar.com.br/house-listing-search/v2/search/list',
    cookies=cookies,
    headers=headers,
    json=json_data,
)

# Note: json_data will not be serialized by requests
# exactly as it was in the original request.
data = '{"context":{"mapShowing":true,"listShowing":true,"userId":"xWOItfnojuBQe215fhhBc49T0JqqyTt0MznGQXwTYZx0IkdFUrZfLg","deviceId":"xWOItfnojuBQe215fhhBc49T0JqqyTt0MznGQXwTYZx0IkdFUrZfLg","numPhotos":12,"isSSR":false},"filters":{"businessContext":"RENT","blocklist":[],"selectedHouses":[],"location":{"coordinate":{"lat":-23.55052,"lng":-46.633309},"viewport":{"east":-46.50439130590819,"north":-23.504561866351537,"south":-23.596462071688684,"west":-46.76222669409179},"neighborhoods":[],"countryCode":"BR"},"priceRange":[],"specialConditions":[],"excludedSpecialConditions":[],"houseSpecs":{"area":{"range":{}},"houseTypes":[],"amenities":[],"installations":[],"bathrooms":{"range":{}},"bedrooms":{"range":{}},"parkingSpace":{"range":{}},"suites":{"range":{}}},"availability":"ANY","occupancy":"ANY","partnerIds":[],"categories":[],"enableFlexibleSearch":true},"sorting":{"criteria":"RELEVANCE","order":"DESC"},"pagination":{"pageSize":12,"offset":0},"slug":"sao-paulo-sp-brasil","fields":["id","coverImage","rent","totalCost","salePrice","iptuPlusCondominium","area","imageList","imageCaptionList","address","regionName","city","visitStatus","activeSpecialConditions","type","forRent","forSale","isPrimaryMarket","bedrooms","parkingSpaces","suites","listingTags","yield","yieldStrategy","neighbourhood","categories","bathrooms","isFurnished","installations","amenities","shortRentDescription","shortSaleDescription"],"locationDescriptions":[{"description":"sao-paulo-sp-brasil"}],"topics":[]}'
response = requests.post(
    'https://apigw.prod.quintoandar.com.br/house-listing-search/v2/search/list',
    cookies=cookies,
    headers=headers,
    data=data,
)

In [8]:
import requests
import pandas as pd
import time

URL = "https://apigw.prod.quintoandar.com.br/house-listing-search/v2/search/list"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Content-Type": "application/json",
    "Origin": "https://www.quintoandar.com.br",
}

all_data = []

for offset in range(0, 50, 25):

    payload = {
        "context": {
            "mapShowing": True,
            "listShowing": True,
            "numPhotos": 12,
            "isSSR": False
        },

        "filters": {
            "businessContext": "RENT",
            "location": {
                "coordinate": {
                    "lat": -23.55052,
                    "lng": -46.633309
                },
                "viewport": {
                    "east": -46.5043,
                    "north": -23.5045,
                    "south": -23.5964,
                    "west": -46.7622
                },
                "countryCode": "BR"
            }
        },

        "sorting": {
            "criteria": "RELEVANCE",
            "order": "DESC"
        },

        "pagination": {
            "pageSize": 12,
            "offset": offset
        },

        "slug": "sao-paulo-sp-brasil",

        "fields": [
            "id",
            "rent",
            "totalCost",
            "iptuPlusCondominium",
            "area",
            "bedrooms",
            "bathrooms",
            "parkingSpaces",
            "suites",
            "neighbourhood",
            "city",
            "address",
            "location"
        ]
    }

    r = requests.post(URL, headers=headers, json=payload)

    if r.status_code != 200:
        print("Erro:", r.text)
        break

    data = r.json()

    listings = data.get("hits", {}).get("hits", [])

    if not listings:
        break

    for item in listings:

        all_data.append({
            "id": source.get("id"),
            "rent": source.get("rent"),
            "total_cost": source.get("totalCost"),
            "condo_iptu": source.get("iptuPlusCondominium"),
            "area": source.get("area"),
            "bedrooms": source.get("bedrooms"),
            "bathrooms": source.get("bathrooms"),
            "parking": source.get("parkingSpaces"),
            "suites": source.get("suites"),
            "bairro": source.get("neighbourhood"),
            "cidade": source.get("city"),
            "endereco": source.get("address"),
            "coordenadas": source.get("location")
        })

    print(f"Offset {offset} coletado")

    time.sleep(1)

df = pd.DataFrame(all_data)

print(df.shape)
df.head()

Offset 0 coletado
Offset 25 coletado
(24, 13)

,id,rent,total_cost,condo_iptu,area,bedrooms,bathrooms,parking,suites,bairro,cidade,endereco,coordenadas
0,894914018,2000,2430,353,23,1,1,0,0,Centro Histórico de São Paulo,São Paulo,Rua Riachuelo,"{'lat': -23.5505278, 'lon': -46.637404}"
1,894914018,2000,2430,353,23,1,1,0,0,Centro Histórico de São Paulo,São Paulo,Rua Riachuelo,"{'lat': -23.5505278, 'lon': -46.637404}"
2,894914018,2000,2430,353,23,1,1,0,0,Centro Histórico de São Paulo,São Paulo,Rua Riachuelo,"{'lat': -23.5505278, 'lon': -46.637404}"
3,894914018,2000,2430,353,23,1,1,0,0,Centro Histórico de São Paulo,São Paulo,Rua Riachuelo,"{'lat': -23.5505278, 'lon': -46.637404}"
4,894914018,2000,2430,353,23,1,1,0,0,Centro Histórico de São Paulo,São Paulo,Rua Riachuelo,"{'lat': -23.5505278, 'lon': -46.637404}"

In [3]:
import requests
import pandas as pd
import time

URL = "https://apigw.prod.quintoandar.com.br/house-listing-search/v2/search/list"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Content-Type": "application/json",
    "Origin": "https://www.quintoandar.com.br"
}

all_data = []

latitudes = [-23.8, -23.7, -23.6, -23.5, -23.4]
longitudes = [-46.8, -46.7, -46.6, -46.5, -46.4]

fields = [

"id",
"rent",
"totalCost",
"iptuPlusCondominium",
"salePrice",

"area",
"bedrooms",
"bathrooms",
"parkingSpaces",
"suites",

"neighbourhood",
"city",
"regionName",
"address",

"type",
"forRent",
"forSale",

"isFurnished",
"isPrimaryMarket",

"amenities",
"installations",

"listingTags",
"categories",

"visitStatus",

"imageList",
"coverImage",

"yield",
"yieldStrategy",

"shortRentDescription",

"activeSpecialConditions"
]

for i in range(len(latitudes)-1):
    for j in range(len(longitudes)-1):

        north = latitudes[i+1]
        south = latitudes[i]
        east = longitudes[j+1]
        west = longitudes[j]

        offset = 0
        page_size = 50

        print(f"Área {i}-{j}")

        while True:

            payload = {
                "context": {
                    "mapShowing": True,
                    "listShowing": True
                },

                "filters": {
                    "businessContext": "RENT",
                    "location": {
                        "coordinate": {
                            "lat": (north + south)/2,
                            "lng": (east + west)/2
                        },
                        "viewport": {
                            "north": north,
                            "south": south,
                            "east": east,
                            "west": west
                        },
                        "countryCode": "BR"
                    }
                },

                "pagination": {
                    "pageSize": page_size,
                    "offset": offset
                },

                "slug": "sao-paulo-sp-brasil",

                "fields": fields
            }

            r = requests.post(URL, headers=headers, json=payload)

            if r.status_code != 200:
                print("Erro:", r.text)
                break

            data = r.json()

            listings = data.get("hits", {}).get("hits", [])

            if not listings:
                break

            for item in listings:

                source = item.get("_source", {})

                source["lat_viewport"] = (north + south)/2
                source["lon_viewport"] = (east + west)/2

                all_data.append(source)

            offset += page_size

            print(len(all_data), "imóveis")

            time.sleep(0.8)

df = pd.DataFrame(all_data)

#df = df.drop_duplicates(subset="id")

#df.to_csv("quintoandar_sp_full.csv", index=False)

print("Total:", len(df))

Área 0-0
48 imóveis
Área 0-1
98 imóveis
148 imóveis
152 imóveis
Área 0-2
202 imóveis
252 imóveis
302 imóveis
352 imóveis
402 imóveis
452 imóveis
502 imóveis
552 imóveis
602 imóveis
652 imóveis
700 imóveis
Área 0-3
720 imóveis
Área 1-0
770 imóveis
820 imóveis
870 imóveis
920 imóveis
970 imóveis
1020 imóveis
1070 imóveis
1120 imóveis
1170 imóveis
1220 imóveis
1270 imóveis
1320 imóveis
1370 imóveis
1420 imóveis
1470 imóveis
1520 imóveis
1570 imóveis
1620 imóveis
1670 imóveis
1720 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 8285f72704e3dcceb29c6c750e06a785"}
Área 1-1
1770 imóveis
1820 imóveis
1870 imóveis
1920 imóveis
1970 imóveis
2020 imóveis
2070 imóveis
2120 imóveis
2170 imóveis
2220 imóveis
2270 imóveis
2320 imóveis
2370 imóveis
2420 imóveis
2470 imóveis
2520 imóveis
2570 imóveis
2620 imóveis
2670 imóveis
2720 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: dbc198eb48ec68c9cd47861bd7f49924"}
Área 1-2
2770 imóveis
2820 imóveis
2870 imóveis
2920 imóveis
2970 imóveis
3020 imóveis
3070 imóveis
3120 imóveis
3170 imóveis
3220 imóveis
3270 imóveis
3320 imóveis
3370 imóveis
3420 imóveis
3470 imóveis
3520 imóveis
3570 imóveis
3620 imóveis
3670 imóveis
3720 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 945d54a064aace6f7786ab2cd2ff308e"}
Área 1-3
3770 imóveis
3820 imóveis
3870 imóveis
3920 imóveis
3970 imóveis
4020 imóveis
4070 imóveis
4120 imóveis
4165 imóveis
Área 2-0
4215 imóveis
4265 imóveis
4315 imóveis
4365 imóveis
4415 imóveis
4465 imóveis
4515 imóveis
4565 imóveis
4615 imóveis
4665 imóveis
4715 imóveis
4765 imóveis
4815 imóveis
4865 imóveis
4915 imóveis
4965 imóveis
5015 imóveis
5065 imóveis
5115 imóveis
5165 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: b8f94c1fd2baeb81d99bdbe018715aed"}
Área 2-1
5215 imóveis
5265 imóveis
5315 imóveis
5365 imóveis
5415 imóveis
5465 imóveis
5515 imóveis
5565 imóveis
5615 imóveis
5665 imóveis
5715 imóveis
5765 imóveis
5815 imóveis
5865 imóveis
5915 imóveis
5965 imóveis
6015 imóveis
6065 imóveis
6115 imóveis
6165 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: d68a8d05c9c72c5efc2554fc5a28290f"}
Área 2-2
6215 imóveis
6265 imóveis
6315 imóveis
6365 imóveis
6415 imóveis
6465 imóveis
6515 imóveis
6565 imóveis
6615 imóveis
6665 imóveis
6715 imóveis
6765 imóveis
6815 imóveis
6865 imóveis
6915 imóveis
6965 imóveis
7015 imóveis
7065 imóveis
7115 imóveis
7165 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 4023261f42b231126440f658e8faf085"}
Área 2-3
7215 imóveis
7265 imóveis
7315 imóveis
7365 imóveis
7415 imóveis
7465 imóveis
7515 imóveis
7565 imóveis
7615 imóveis
7665 imóveis
7715 imóveis
7765 imóveis
7815 imóveis
7865 imóveis
7915 imóveis
7965 imóveis
8015 imóveis
8065 imóveis
8115 imóveis
8165 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 5dcecde9d617117feb3f599d956ee8bb"}
Área 3-0
8215 imóveis
8265 imóveis
8315 imóveis
8365 imóveis
8415 imóveis
8465 imóveis
8515 imóveis
8565 imóveis
8615 imóveis
8665 imóveis
8715 imóveis
8765 imóveis
8791 imóveis
Área 3-1
8841 imóveis
8891 imóveis
8941 imóveis
8991 imóveis
9041 imóveis
9091 imóveis
9141 imóveis
9191 imóveis
9241 imóveis
9291 imóveis
9341 imóveis
9391 imóveis
9441 imóveis
9491 imóveis
9541 imóveis
9591 imóveis
9641 imóveis
9691 imóveis
9741 imóveis
9791 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: b77d6095a083d12af58a478ad2bcd0f4"}
Área 3-2
9841 imóveis
9891 imóveis
9941 imóveis
9991 imóveis
10041 imóveis
10091 imóveis
10141 imóveis
10191 imóveis
10241 imóveis
10291 imóveis
10341 imóveis
10391 imóveis
10441 imóveis
10491 imóveis
10541 imóveis
10591 imóveis
10641 imóveis
10691 imóveis
10741 imóveis
10791 imóveis
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 04f48169ee79a0c7df5760d9f942624a"}
Área 3-3
10841 imóveis
10891 imóveis
10941 imóveis
10991 imóveis
11041 imóveis
11091 imóveis
11113 imóveis
Total: 10407

In [17]:
df.columns

Index(['id', 'type', 'area', 'bathrooms', 'bedrooms', 'suites',
       'parkingSpaces', 'amenities', 'installations', 'totalCost', 'rent',
       'iptuPlusCondominium', 'salePrice', 'address', 'city', 'neighbourhood',
       'regionName', 'isSecondaryHouse', 'coverImage', 'imageList', 'forRent',
       'forSale', 'isPrimaryMarket', 'visitStatus', 'isFurnished',
       'shortRentDescription', 'lat_viewport', 'lon_viewport',
       'activeSpecialConditions', 'yield', 'yieldStrategy', 'categories'],
      dtype='object')

In [24]:
df[['id', 'type', 'area', 'bathrooms', 'bedrooms', 'suites',
       'parkingSpaces', 'amenities', 'installations', 'totalCost', 'rent',
       'iptuPlusCondominium', 'salePrice', 'address', 'city', 'neighbourhood']]

,id,type,area,bathrooms,bedrooms,suites,parkingSpaces,amenities,installations,totalCost,rent,iptuPlusCondominium,salePrice,address,city,neighbourhood
0,895045269,Casa,278.0,5.0,4.0,3.0,2.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...","[CORRIMAO, AREA_VERDE, VAGA_DE_GARAGEM_ACESSIVEL]",7976,6900,783,0.0,Rua Célso Mantovani,São Paulo,Parque do Castelo
1,895326006,Casa,210.0,3.0,3.0,1.0,3.0,"[VISTA_LIVRE, COOKTOP, QUARTOS_E_CORREDORES_CO...","[CORRIMAO, VAGA_DE_GARAGEM_ACESSIVEL, CHURRASQ...",17089,16000,410,0.0,Rua Antônio Machado Sant8217anna,São Paulo,Parque Esmeralda
2,894886337,Casa,50.0,1.0,1.0,0.0,1.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[LAVANDERIA_NO_PREDIO],1863,1787,0,0.0,Rua Baltazar Soares,São Paulo,Cidade Dutra
3,894996197,Apartamento,65.0,1.0,2.0,0.0,0.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, ARMAR...",[],2124,1660,400,280000.0,Avenida Senador Teotônio Vilela,São Paulo,Cidade Dutra
4,895128093,Casa,690.0,7.0,6.0,4.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...","[CORRIMAO, AREA_VERDE, LAVANDERIA_NO_PREDIO, V...",15165,12959,1656,2500000.0,Rua Professor Cândido Nogueira da Motta,São Paulo,Interlagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10894,894500473,Casa,50.0,1.0,1.0,0.0,0.0,"[RUA_SILENCIOSA, ARMARIOS_NA_COZINHA]",[PERTO_DE_METRO_OU_TREM],1000,960,0,285000.0,Rua Benevenuto de Magalhães Taques,São Paulo,Ermelino Matarazzo
10895,894907307,Casa,30.0,1.0,1.0,0.0,3.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...","[VAGA_DE_GARAGEM_ACESSIVEL, PERTO_DE_METRO_OU_...",1288,1220,16,230000.0,Rua Manuel de Mattos Godinho,São Paulo,Jardim Matarazzo
10896,895195216,Casa,540.0,1.0,1.0,0.0,5.0,"[RUA_SILENCIOSA, SOMENTE_UMA_CASA_NO_TERRENO, ...","[VAGA_DE_GARAGEM_ACESSIVEL, RAMPAS_DE_ACESSO]",5799,4500,1108,1350000.0,Rua Guilherme de Oliveira Sá,São Paulo,Parque Boturussu
10897,895144593,Casa,434.0,3.0,4.0,1.0,2.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...",[],6125,5500,392,979000.0,Rua Boaventura Rodrigues da Silva,São Paulo,Parque Boturussu
10898,894501507,Casa,50.0,1.0,1.0,0.0,0.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...",[CORRIMAO],1133,1030,59,0.0,Rua Regiani,Guarulhos,Cidade Jardim Cumbica

### RODAR ESSE SCRIPT ABAIXO

In [18]:
import requests
import pandas as pd
import numpy as np
import time

URL = "https://apigw.prod.quintoandar.com.br/house-listing-search/v2/search/list"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Content-Type": "application/json",
    "Origin": "https://www.quintoandar.com.br"
}

# bounding box grande da região de São Paulo
lat_min = -23.85
lat_max = -23.35

lon_min = -46.85
lon_max = -46.35

step = 0.04

latitudes = np.arange(lat_min, lat_max, step)
longitudes = np.arange(lon_min, lon_max, step)

print("Total de áreas:", len(latitudes) * len(longitudes))

fields = [
"id",
"rent",
"totalCost",
"iptuPlusCondominium",
"salePrice",

"area",
"bedrooms",
"bathrooms",
"parkingSpaces",
"suites",

"neighbourhood",
"city",
"regionName",
"address",
"location",

"type",
"forRent",
"forSale",

"isFurnished",
"isPrimaryMarket",

"amenities",
"installations",

"listingTags",
"categories",

"visitStatus",

"imageList",
"coverImage",

"yield",
"yieldStrategy",

"shortRentDescription",

"activeSpecialConditions"
]

all_data = []

for lat in latitudes:
    for lon in longitudes:

        north = lat + step
        south = lat
        east = lon + step
        west = lon

        offset = 0
        page_size = 100

        print(f"Coletando viewport: {south},{west}")

        while True:

            payload = {
                "context": {
                    "mapShowing": True,
                    "listShowing": True
                },

                "filters": {
                    "businessContext": "RENT",
                    "location": {
                        "coordinate": {
                            "lat": (north + south) / 2,
                            "lng": (east + west) / 2
                        },
                        "viewport": {
                            "north": north,
                            "south": south,
                            "east": east,
                            "west": west
                        },
                        "countryCode": "BR"
                    }
                },

                "pagination": {
                    "pageSize": page_size,
                    "offset": offset
                },

                "slug": "sao-paulo-sp-brasil",

                "fields": fields
            }

            r = requests.post(URL, headers=headers, json=payload)

            if r.status_code != 200:
                print("Erro:", r.text)
                break

            data = r.json()

            listings = data.get("hits", {}).get("hits", [])

            if not listings:
                break

            for item in listings:

                source = item.get("_source", {})

                source["lat_viewport"] = (north + south) / 2
                source["lon_viewport"] = (east + west) / 2

                all_data.append(source)

            offset += page_size

            print(len(all_data), "imóveis coletados")

            time.sleep(0.7)

df = pd.DataFrame(all_data)

df = df.drop_duplicates(subset="id")
df

# filtrar apenas cidade de São Paulo
#df = df[df["city"] == "São Paulo"]

#df.to_csv("quintoandar_sp_full.csv", index=False)

print("Total final:", len(df))

Total de áreas: 169
Coletando viewport: -23.85,-46.85
Coletando viewport: -23.85,-46.81
Coletando viewport: -23.85,-46.77
Coletando viewport: -23.85,-46.730000000000004
Coletando viewport: -23.85,-46.690000000000005
Coletando viewport: -23.85,-46.650000000000006
Coletando viewport: -23.85,-46.61000000000001
Coletando viewport: -23.85,-46.57000000000001
Coletando viewport: -23.85,-46.53000000000001
Coletando viewport: -23.85,-46.49000000000001
Coletando viewport: -23.85,-46.45000000000001
Coletando viewport: -23.85,-46.41000000000001
Coletando viewport: -23.85,-46.37000000000001
Coletando viewport: -23.810000000000002,-46.85
Coletando viewport: -23.810000000000002,-46.81
Coletando viewport: -23.810000000000002,-46.77
Coletando viewport: -23.810000000000002,-46.730000000000004
2 imóveis coletados
Coletando viewport: -23.810000000000002,-46.690000000000005
6 imóveis coletados
Coletando viewport: -23.810000000000002,-46.650000000000006
7 imóveis coletados
Coletando viewport: -23.810000000000002,-46.61000000000001
Coletando viewport: -23.810000000000002,-46.57000000000001
Coletando viewport: -23.810000000000002,-46.53000000000001
Coletando viewport: -23.810000000000002,-46.49000000000001
Coletando viewport: -23.810000000000002,-46.45000000000001
Coletando viewport: -23.810000000000002,-46.41000000000001
Coletando viewport: -23.810000000000002,-46.37000000000001
Coletando viewport: -23.770000000000003,-46.85
Coletando viewport: -23.770000000000003,-46.81
Coletando viewport: -23.770000000000003,-46.77
Coletando viewport: -23.770000000000003,-46.730000000000004
21 imóveis coletados
Coletando viewport: -23.770000000000003,-46.690000000000005
33 imóveis coletados
Coletando viewport: -23.770000000000003,-46.650000000000006
34 imóveis coletados
Coletando viewport: -23.770000000000003,-46.61000000000001
52 imóveis coletados
Coletando viewport: -23.770000000000003,-46.57000000000001
108 imóveis coletados
Coletando viewport: -23.770000000000003,-46.53000000000001
111 imóveis coletados
Coletando viewport: -23.770000000000003,-46.49000000000001
113 imóveis coletados
Coletando viewport: -23.770000000000003,-46.45000000000001
Coletando viewport: -23.770000000000003,-46.41000000000001
Coletando viewport: -23.770000000000003,-46.37000000000001
Coletando viewport: -23.730000000000004,-46.85
Coletando viewport: -23.730000000000004,-46.81
117 imóveis coletados
Coletando viewport: -23.730000000000004,-46.77
130 imóveis coletados
Coletando viewport: -23.730000000000004,-46.730000000000004
208 imóveis coletados
Coletando viewport: -23.730000000000004,-46.690000000000005
308 imóveis coletados
311 imóveis coletados
Coletando viewport: -23.730000000000004,-46.650000000000006
399 imóveis coletados
Coletando viewport: -23.730000000000004,-46.61000000000001
499 imóveis coletados
523 imóveis coletados
Coletando viewport: -23.730000000000004,-46.57000000000001
623 imóveis coletados
723 imóveis coletados
823 imóveis coletados
923 imóveis coletados
1003 imóveis coletados
Coletando viewport: -23.730000000000004,-46.53000000000001
1100 imóveis coletados
Coletando viewport: -23.730000000000004,-46.49000000000001
1102 imóveis coletados
Coletando viewport: -23.730000000000004,-46.45000000000001
1114 imóveis coletados
Coletando viewport: -23.730000000000004,-46.41000000000001
1120 imóveis coletados
Coletando viewport: -23.730000000000004,-46.37000000000001
Coletando viewport: -23.690000000000005,-46.85
1127 imóveis coletados
Coletando viewport: -23.690000000000005,-46.81
1165 imóveis coletados
Coletando viewport: -23.690000000000005,-46.77
1265 imóveis coletados
1284 imóveis coletados
Coletando viewport: -23.690000000000005,-46.730000000000004
1384 imóveis coletados
1484 imóveis coletados
1584 imóveis coletados
1684 imóveis coletados
1686 imóveis coletados
Coletando viewport: -23.690000000000005,-46.690000000000005
1786 imóveis coletados
1886 imóveis coletados
1986 imóveis coletados
2086 imóveis coletados
2186 imóveis coletados
2266 imóveis coletados
Coletando viewport: -23.690000000000005,-46.650000000000006
2366 imóveis coletados
2466 imóveis coletados
2546 imóveis coletados
Coletando viewport: -23.690000000000005,-46.61000000000001
2646 imóveis coletados
2746 imóveis coletados
2792 imóveis coletados
Coletando viewport: -23.690000000000005,-46.57000000000001
2892 imóveis coletados
2992 imóveis coletados
3092 imóveis coletados
3192 imóveis coletados
3292 imóveis coletados
3356 imóveis coletados
Coletando viewport: -23.690000000000005,-46.53000000000001
3456 imóveis coletados
3556 imóveis coletados
3624 imóveis coletados
Coletando viewport: -23.690000000000005,-46.49000000000001
3697 imóveis coletados
Coletando viewport: -23.690000000000005,-46.45000000000001
3723 imóveis coletados
Coletando viewport: -23.690000000000005,-46.41000000000001
3724 imóveis coletados
Coletando viewport: -23.690000000000005,-46.37000000000001
3726 imóveis coletados
Coletando viewport: -23.650000000000006,-46.85
3803 imóveis coletados
Coletando viewport: -23.650000000000006,-46.81
3903 imóveis coletados
3912 imóveis coletados
Coletando viewport: -23.650000000000006,-46.77
4012 imóveis coletados
4112 imóveis coletados
4212 imóveis coletados
4312 imóveis coletados
4412 imóveis coletados
4512 imóveis coletados
4612 imóveis coletados
4712 imóveis coletados
4812 imóveis coletados
4912 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 64e45af03c9368fa96401d195d18c449"}
Coletando viewport: -23.650000000000006,-46.730000000000004
5012 imóveis coletados
5112 imóveis coletados
5212 imóveis coletados
5312 imóveis coletados
5412 imóveis coletados
5512 imóveis coletados
5612 imóveis coletados
5712 imóveis coletados
5812 imóveis coletados
5912 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 8cf9b82951f7635af29c2055db6ba2ba"}
Coletando viewport: -23.650000000000006,-46.690000000000005
6012 imóveis coletados
6112 imóveis coletados
6212 imóveis coletados
6312 imóveis coletados
6412 imóveis coletados
6512 imóveis coletados
6612 imóveis coletados
6712 imóveis coletados
6812 imóveis coletados
6912 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: eb465e651d235955b8d32373670766a7"}
Coletando viewport: -23.650000000000006,-46.650000000000006
7012 imóveis coletados
7112 imóveis coletados
7212 imóveis coletados
7312 imóveis coletados
7412 imóveis coletados
7512 imóveis coletados
7612 imóveis coletados
7712 imóveis coletados
7812 imóveis coletados
7862 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: d11eb33c2e9f68565553e6c3f6bc5e77"}
Coletando viewport: -23.650000000000006,-46.61000000000001
7962 imóveis coletados
8062 imóveis coletados
8162 imóveis coletados
8262 imóveis coletados
8310 imóveis coletados
Coletando viewport: -23.650000000000006,-46.57000000000001
8410 imóveis coletados
8510 imóveis coletados
8610 imóveis coletados
8675 imóveis coletados
Coletando viewport: -23.650000000000006,-46.53000000000001
8775 imóveis coletados
8875 imóveis coletados
8975 imóveis coletados
9003 imóveis coletados
Coletando viewport: -23.650000000000006,-46.49000000000001
9084 imóveis coletados
Coletando viewport: -23.650000000000006,-46.45000000000001
9110 imóveis coletados
Coletando viewport: -23.650000000000006,-46.41000000000001
9112 imóveis coletados
Coletando viewport: -23.650000000000006,-46.37000000000001
9113 imóveis coletados
Coletando viewport: -23.610000000000007,-46.85
9213 imóveis coletados
9313 imóveis coletados
9344 imóveis coletados
Coletando viewport: -23.610000000000007,-46.81
9444 imóveis coletados
9544 imóveis coletados
9593 imóveis coletados
Coletando viewport: -23.610000000000007,-46.77
9693 imóveis coletados
9793 imóveis coletados
9893 imóveis coletados
9993 imóveis coletados
10093 imóveis coletados
10159 imóveis coletados
Coletando viewport: -23.610000000000007,-46.730000000000004
10259 imóveis coletados
10359 imóveis coletados
10459 imóveis coletados

10559 imóveis coletados
10659 imóveis coletados
10759 imóveis coletados
10859 imóveis coletados
10959 imóveis coletados
10961 imóveis coletados
Coletando viewport: -23.610000000000007,-46.690000000000005
11061 imóveis coletados
11161 imóveis coletados
11261 imóveis coletados
11361 imóveis coletados
11461 imóveis coletados
11561 imóveis coletados
11661 imóveis coletados
11761 imóveis coletados
11861 imóveis coletados
11961 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 03b97fe93949b6fd9bfca77caabf5dc6"}
Coletando viewport: -23.610000000000007,-46.650000000000006
12061 imóveis coletados
12161 imóveis coletados
12261 imóveis coletados
12361 imóveis coletados
12461 imóveis coletados
12561 imóveis coletados
12661 imóveis coletados
12761 imóveis coletados
12861 imóveis coletados
12961 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 69320863d2414c3a789eb88bc4d4cb5c"}
Coletando viewport: -23.610000000000007,-46.61000000000001
13061 imóveis coletados
13161 imóveis coletados
13261 imóveis coletados
13361 imóveis coletados
13461 imóveis coletados
13561 imóveis coletados
13661 imóveis coletados
13761 imóveis coletados
13861 imóveis coletados
13895 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 8f10cb2e8d19981eefcf81524d017a89"}
Coletando viewport: -23.610000000000007,-46.57000000000001
13995 imóveis coletados
14095 imóveis coletados
14195 imóveis coletados
14295 imóveis coletados
14395 imóveis coletados
14495 imóveis coletados
14595 imóveis coletados
14667 imóveis coletados
Coletando viewport: -23.610000000000007,-46.53000000000001
14767 imóveis coletados
14867 imóveis coletados
14967 imóveis coletados
15000 imóveis coletados
Coletando viewport: -23.610000000000007,-46.49000000000001
15100 imóveis coletados
15200 imóveis coletados
15202 imóveis coletados
Coletando viewport: -23.610000000000007,-46.45000000000001
15302 imóveis coletados
15311 imóveis coletados
Coletando viewport: -23.610000000000007,-46.41000000000001
15349 imóveis coletados
Coletando viewport: -23.610000000000007,-46.37000000000001
Coletando viewport: -23.570000000000007,-46.85
15449 imóveis coletados
15488 imóveis coletados
Coletando viewport: -23.570000000000007,-46.81
15588 imóveis coletados
15688 imóveis coletados
15788 imóveis coletados
15888 imóveis coletados
15988 imóveis coletados
16000 imóveis coletados
Coletando viewport: -23.570000000000007,-46.77
16100 imóveis coletados
16200 imóveis coletados
16300 imóveis coletados
16400 imóveis coletados
16469 imóveis coletados
Coletando viewport: -23.570000000000007,-46.730000000000004
16569 imóveis coletados
16669 imóveis coletados
16769 imóveis coletados
16869 imóveis coletados
16969 imóveis coletados
17069 imóveis coletados
17169 imóveis coletados
17269 imóveis coletados
17369 imóveis coletados
17469 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 59df6bbb0cbc5e095299970741962d71"}
Coletando viewport: -23.570000000000007,-46.690000000000005
17569 imóveis coletados
17669 imóveis coletados
17769 imóveis coletados
17869 imóveis coletados
17969 imóveis coletados
18069 imóveis coletados
18169 imóveis coletados
18269 imóveis coletados
18369 imóveis coletados
18469 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 09d08441a4f24d7b897355f27f70417d"}
Coletando viewport: -23.570000000000007,-46.650000000000006
18569 imóveis coletados
18669 imóveis coletados
18769 imóveis coletados
18869 imóveis coletados
18969 imóveis coletados
19069 imóveis coletados
19169 imóveis coletados
19269 imóveis coletados
19369 imóveis coletados
19469 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 7641ff87947c060291efdf853b87b4f6"}
Coletando viewport: -23.570000000000007,-46.61000000000001
19569 imóveis coletados
19669 imóveis coletados
19769 imóveis coletados
19869 imóveis coletados
19969 imóveis coletados
20069 imóveis coletados
20169 imóveis coletados
20269 imóveis coletados
20369 imóveis coletados
20469 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 686493a5d127b8565f80e1419b75f755"}
Coletando viewport: -23.570000000000007,-46.57000000000001
20569 imóveis coletados
20669 imóveis coletados
20769 imóveis coletados
20869 imóveis coletados
20969 imóveis coletados
21069 imóveis coletados
21169 imóveis coletados
21269 imóveis coletados
21369 imóveis coletados
21469 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: 126f821d6fb4adcd3b073924a5017876"}
Coletando viewport: -23.570000000000007,-46.53000000000001
21569 imóveis coletados
21669 imóveis coletados
21769 imóveis coletados
21869 imóveis coletados
21969 imóveis coletados
22069 imóveis coletados
22166 imóveis coletados
Coletando viewport: -23.570000000000007,-46.49000000000001
22266 imóveis coletados
22366 imóveis coletados
22466 imóveis coletados
22566 imóveis coletados
22666 imóveis coletados
22766 imóveis coletados
22819 imóveis coletados
Coletando viewport: -23.570000000000007,-46.45000000000001
22919 imóveis coletados
23019 imóveis coletados
23099 imóveis coletados
Coletando viewport: -23.570000000000007,-46.41000000000001
23199 imóveis coletados
23203 imóveis coletados
Coletando viewport: -23.570000000000007,-46.37000000000001
23264 imóveis coletados
Coletando viewport: -23.53000000000001,-46.85
23364 imóveis coletados
23464 imóveis coletados
23468 imóveis coletados
Coletando viewport: -23.53000000000001,-46.81
23568 imóveis coletados
23604 imóveis coletados
Coletando viewport: -23.53000000000001,-46.77
23704 imóveis coletados
23804 imóveis coletados
23819 imóveis coletados
Coletando viewport: -23.53000000000001,-46.730000000000004
23919 imóveis coletados
24019 imóveis coletados
24119 imóveis coletados
24219 imóveis coletados
24319 imóveis coletados
24419 imóveis coletados
24519 imóveis coletados
24589 imóveis coletados
Coletando viewport: -23.53000000000001,-46.690000000000005
24689 imóveis coletados
24789 imóveis coletados
24889 imóveis coletados
24989 imóveis coletados
25089 imóveis coletados
25189 imóveis coletados
25289 imóveis coletados
25389 imóveis coletados
25489 imóveis coletados
25589 imóveis coletados
Erro: {"code":400,"message":"Validation failed: [searchCriteria.pagination: Pagination exceeds the maximum limit] - traceId: fbf8a24caf8049c064ae73b032157ccd"}
Coletando viewport: -23.53000000000001,-46.650000000000006
25689 imóveis coletados
25789 imóveis coletados
25889 imóveis coletados
25989 imóveis coletados
26089 imóveis coletados
26189 imóveis coletados
26289 imóveis coletados
26389 imóveis coletados
26479 imóveis coletados
Coletando viewport: -23.53000000000001,-46.61000000000001
26579 imóveis coletados
26679 imóveis coletados
26779 imóveis coletados
26879 imóveis coletados
26979 imóveis coletados
26983 imóveis coletados
Coletando viewport: -23.53000000000001,-46.57000000000001
27083 imóveis coletados
27183 imóveis coletados
27283 imóveis coletados
27383 imóveis coletados
27482 imóveis coletados
Coletando viewport: -23.53000000000001,-46.53000000000001
27582 imóveis coletados
27682 imóveis coletados
27782 imóveis coletados
27882 imóveis coletados
27949 imóveis coletados
Coletando viewport: -23.53000000000001,-46.49000000000001
28049 imóveis coletados
28149 imóveis coletados
28235 imóveis coletados
Coletando viewport: -23.53000000000001,-46.45000000000001
28335 imóveis coletados
28435 imóveis coletados
28479 imóveis coletados
Coletando viewport: -23.53000000000001,-46.41000000000001
28546 imóveis coletados
Coletando viewport: -23.53000000000001,-46.37000000000001
28601 imóveis coletados
Coletando viewport: -23.49000000000001,-46.85
28701 imóveis coletados

28713 imóveis coletados
Coletando viewport: -23.49000000000001,-46.81
28717 imóveis coletados
Coletando viewport: -23.49000000000001,-46.77
28817 imóveis coletados
28890 imóveis coletados
Coletando viewport: -23.49000000000001,-46.730000000000004
28990 imóveis coletados
29090 imóveis coletados
29190 imóveis coletados
29202 imóveis coletados
Coletando viewport: -23.49000000000001,-46.690000000000005
29302 imóveis coletados
29402 imóveis coletados
29502 imóveis coletados
29505 imóveis coletados
Coletando viewport: -23.49000000000001,-46.650000000000006
29605 imóveis coletados
29705 imóveis coletados
29805 imóveis coletados
29905 imóveis coletados
30005 imóveis coletados
30105 imóveis coletados
30174 imóveis coletados
Coletando viewport: -23.49000000000001,-46.61000000000001
30274 imóveis coletados
30374 imóveis coletados
30474 imóveis coletados
30574 imóveis coletados
30674 imóveis coletados
30774 imóveis coletados
30834 imóveis coletados
Coletando viewport: -23.49000000000001,-46.57000000000001
30934 imóveis coletados
31034 imóveis coletados
31134 imóveis coletados
31234 imóveis coletados
31279 imóveis coletados
Coletando viewport: -23.49000000000001,-46.53000000000001
31379 imóveis coletados
31459 imóveis coletados
Coletando viewport: -23.49000000000001,-46.49000000000001
31482 imóveis coletados
Coletando viewport: -23.49000000000001,-46.45000000000001
31526 imóveis coletados
Coletando viewport: -23.49000000000001,-46.41000000000001
31549 imóveis coletados
Coletando viewport: -23.49000000000001,-46.37000000000001
31555 imóveis coletados
Coletando viewport: -23.45000000000001,-46.85
31559 imóveis coletados
Coletando viewport: -23.45000000000001,-46.81
31563 imóveis coletados
Coletando viewport: -23.45000000000001,-46.77
31596 imóveis coletados
Coletando viewport: -23.45000000000001,-46.730000000000004
31642 imóveis coletados
Coletando viewport: -23.45000000000001,-46.690000000000005
31643 imóveis coletados
Coletando viewport: -23.45000000000001,-46.650000000000006
31658 imóveis coletados
Coletando viewport: -23.45000000000001,-46.61000000000001
31734 imóveis coletados
Coletando viewport: -23.45000000000001,-46.57000000000001
31834 imóveis coletados
31934 imóveis coletados
32034 imóveis coletados
32095 imóveis coletados
Coletando viewport: -23.45000000000001,-46.53000000000001
32182 imóveis coletados
Coletando viewport: -23.45000000000001,-46.49000000000001
32187 imóveis coletados
Coletando viewport: -23.45000000000001,-46.45000000000001
32239 imóveis coletados
Coletando viewport: -23.45000000000001,-46.41000000000001
32299 imóveis coletados
Coletando viewport: -23.45000000000001,-46.37000000000001
Coletando viewport: -23.41000000000001,-46.85
Coletando viewport: -23.41000000000001,-46.81
Coletando viewport: -23.41000000000001,-46.77
32306 imóveis coletados
Coletando viewport: -23.41000000000001,-46.730000000000004
Coletando viewport: -23.41000000000001,-46.690000000000005
Coletando viewport: -23.41000000000001,-46.650000000000006
Coletando viewport: -23.41000000000001,-46.61000000000001
Coletando viewport: -23.41000000000001,-46.57000000000001
32308 imóveis coletados
Coletando viewport: -23.41000000000001,-46.53000000000001
32321 imóveis coletados
Coletando viewport: -23.41000000000001,-46.49000000000001
32323 imóveis coletados
Coletando viewport: -23.41000000000001,-46.45000000000001
32343 imóveis coletados
Coletando viewport: -23.41000000000001,-46.41000000000001
32362 imóveis coletados
Coletando viewport: -23.41000000000001,-46.37000000000001
Coletando viewport: -23.37000000000001,-46.85
Coletando viewport: -23.37000000000001,-46.81
Coletando viewport: -23.37000000000001,-46.77
Coletando viewport: -23.37000000000001,-46.730000000000004
Coletando viewport: -23.37000000000001,-46.690000000000005
Coletando viewport: -23.37000000000001,-46.650000000000006
Coletando viewport: -23.37000000000001,-46.61000000000001
Coletando viewport: -23.37000000000001,-46.57000000000001
Coletando viewport: -23.37000000000001,-46.53000000000001
Coletando viewport: -23.37000000000001,-46.49000000000001
Coletando viewport: -23.37000000000001,-46.45000000000001
Coletando viewport: -23.37000000000001,-46.41000000000001
Coletando viewport: -23.37000000000001,-46.37000000000001
Total final: 30413

In [21]:
df

,id,type,area,bathrooms,bedrooms,suites,parkingSpaces,amenities,installations,totalCost,...,isPrimaryMarket,visitStatus,isFurnished,shortRentDescription,lat_viewport,lon_viewport,activeSpecialConditions,yield,yieldStrategy,categories
0,895407132,Casa,80.0,1.0,2.0,0.0,1.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, AREA_...",[VAGA_DE_GARAGEM_ACESSIVEL],1563,...,False,ACCEPT_NEW,False,Casa para aluguel com 2 quartos.,-23.79,-46.71,NaN,NaN,NaN,NaN
1,895598034,Casa,50.0,1.0,1.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[LAVANDERIA_NO_PREDIO],1355,...,False,ACCEPT_NEW,False,Casa para aluguel com 1 quarto.,-23.79,-46.71,NaN,NaN,NaN,NaN
2,895521778,Casa,45.0,1.0,2.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[],999,...,False,ACCEPT_NEW,False,Casa para aluguel no Jardim Morais Prado com 2...,-23.79,-46.67,[Exclusivity],NaN,NaN,NaN
3,895270262,Casa,250.0,4.0,3.0,3.0,2.0,"[VISTA_LIVRE, COOKTOP, QUARTOS_E_CORREDORES_CO...","[LAVANDERIA_NO_PREDIO, VAGA_DE_GARAGEM_ACESSIVEL]",3732,...,False,ACCEPT_NEW,True,Aluguel de casa mobiliada com 3 quartos e vara...,-23.79,-46.67,NaN,0.0061,CONTRACT,NaN
4,895521782,Apartamento,45.0,1.0,1.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[],996,...,False,ACCEPT_NEW,False,Alugar apartamento com 1 quarto e permite anim...,-23.79,-46.67,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32357,895536219,Casa,50.0,1.0,1.0,0.0,0.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, LUMIN...","[CORRIMAO, VAGA_DE_GARAGEM_ACESSIVEL, RAMPAS_D...",1206,...,False,ACCEPT_NEW,False,Casa para alugar com 1 quarto.,-23.39,-46.39,NaN,NaN,NaN,NaN
32358,895376426,Casa,90.0,1.0,2.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[PISO_TATIL],1668,...,False,ACCEPT_NEW,False,Alugar casa com 2 quartos e varanda.,-23.39,-46.39,NaN,NaN,NaN,NaN
32359,894865833,Casa,200.0,1.0,2.0,0.0,0.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...","[CORRIMAO, PISO_TATIL]",2627,...,False,ACCEPT_NEW,False,Casa com 2 quartos disponível para alugar. Ide...,-23.39,-46.39,[Exclusivity],NaN,NaN,NaN
32360,895472906,StudioOuKitchenette,36.0,1.0,2.0,0.0,0.0,[RUA_SILENCIOSA],[],1671,...,False,ACCEPT_NEW,False,Kitnet com 2 quartos para alugar.,-23.39,-46.39,[Exclusivity],NaN,NaN,NaN
32361,895351163,Apartamento,53.0,1.0,2.0,0.0,1.0,"[VISTA_LIVRE, RUA_SILENCIOSA, ARMARIOS_NOS_BAN...","[SALAO_DE_FESTAS, VAGA_DE_GARAGEM_ACESSIVEL, Q...",1428,...,False,ACCEPT_NEW,False,Aluguel de apartamento com 2 quartos.,-23.39,-46.39,[Exclusivity],NaN,NaN,NaN

In [22]:
caminho = "/home/felipe/Projeto/Portfolio/Portfolio2/Regression_PriceHouse/data/raw/quintoandar/"

df.to_parquet(caminho + "quintoandar_sp_completo.parquet", index=False)

In [23]:
df[df["city"] == "São Paulo"]

,id,type,area,bathrooms,bedrooms,suites,parkingSpaces,amenities,installations,totalCost,...,isPrimaryMarket,visitStatus,isFurnished,shortRentDescription,lat_viewport,lon_viewport,activeSpecialConditions,yield,yieldStrategy,categories
0,895407132,Casa,80.0,1.0,2.0,0.0,1.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, AREA_...",[VAGA_DE_GARAGEM_ACESSIVEL],1563,...,False,ACCEPT_NEW,False,Casa para aluguel com 2 quartos.,-23.79,-46.71,NaN,NaN,NaN,NaN
1,895598034,Casa,50.0,1.0,1.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[LAVANDERIA_NO_PREDIO],1355,...,False,ACCEPT_NEW,False,Casa para aluguel com 1 quarto.,-23.79,-46.71,NaN,NaN,NaN,NaN
2,895521778,Casa,45.0,1.0,2.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[],999,...,False,ACCEPT_NEW,False,Casa para aluguel no Jardim Morais Prado com 2...,-23.79,-46.67,[Exclusivity],NaN,NaN,NaN
3,895270262,Casa,250.0,4.0,3.0,3.0,2.0,"[VISTA_LIVRE, COOKTOP, QUARTOS_E_CORREDORES_CO...","[LAVANDERIA_NO_PREDIO, VAGA_DE_GARAGEM_ACESSIVEL]",3732,...,False,ACCEPT_NEW,True,Aluguel de casa mobiliada com 3 quartos e vara...,-23.79,-46.67,NaN,0.0061,CONTRACT,NaN
4,895521782,Apartamento,45.0,1.0,1.0,0.0,0.0,"[VISTA_LIVRE, QUARTOS_E_CORREDORES_COM_PORTAS_...",[],996,...,False,ACCEPT_NEW,False,Alugar apartamento com 1 quarto e permite anim...,-23.79,-46.67,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32301,895307842,Casa,60.0,2.0,2.0,0.0,4.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...","[VAGA_DE_GARAGEM_ACESSIVEL, PERTO_DE_METRO_OU_...",3501,...,False,ACCEPT_NEW,False,Casa para alugar com 2 quartos.,-23.39,-46.75,NaN,NaN,NaN,NaN
32302,895280994,Casa,301.0,2.0,3.0,2.0,3.0,[PODE_TER_ANIMAIS_DE_ESTIMACAO],NaN,3711,...,False,ACCEPT_NEW,True,"Casa para alugar: 3 quartos, 2 suítes, mobilia...",-23.39,-46.75,[Exclusivity],NaN,NaN,NaN
32303,895307848,Casa,40.0,1.0,1.0,0.0,4.0,"[QUARTOS_E_CORREDORES_COM_PORTAS_AMPLAS, RUA_S...","[VAGA_DE_GARAGEM_ACESSIVEL, CHURRASQUEIRA, PER...",2459,...,False,ACCEPT_NEW,False,"Casa para alugar em Perus: 1 quarto, aceita pets.",-23.39,-46.75,NaN,NaN,NaN,NaN
32304,895387171,Apartamento,42.0,1.0,2.0,0.0,1.0,"[VISTA_LIVRE, RUA_SILENCIOSA, BOX, SOL_DA_MANH...","[SALAO_DE_FESTAS, AREA_VERDE, VAGA_DE_GARAGEM_...",2790,...,False,ACCEPT_NEW,False,Alugar apartamento com 2 quartos e churrasquei...,-23.39,-46.75,NaN,NaN,NaN,NaN
32305,895283851,Casa,150.0,1.0,2.0,0.0,0.0,"[VISTA_LIVRE, VARANDA, SOL_DA_MANHA, LUMINOSID...",[],1563,...,False,ACCEPT_NEW,False,Casa para alugar na Vila Fanton com 2 quartos.,-23.39,-46.75,[Exclusivity],NaN,NaN,NaN